### ISSUE TITLE
Focus event lossage with self-referential networkHold 

### ISSUE THREAD

**Issue by deepfire** [reflex-frp/reflex-vty#10]
Two exhibits from https://gist.github.com/deepfire-pusher/fe13848dc810ada606e79964b3549418

The problem, roughly: focus events are not delivered, when a `networkHold` expression's output `Event` is looped unto the network being switched to (but of course, without a true circular data dependency). The lack of focus change events is relieved, when this loop is broken.

First, setting:

1. A small network consisting of two widgets, one of them affecting the other:
   - a menu-like list of button-like, focusable widgets, emitting individual events of the same type -- in response to `Enter` (when focused) or mouse clicks
   - a text input that defines a simple filter for the list

2. Since the list content is subordinate to the text input's filter definition, the network configuration requires switching, so enters `networkHold`

3. Since both elements -- the menu and the text are supposed to consume input at the same time, they both need to have focus -- so they need to reside in separate panes that both need to have focus, when their parent does.

This is seemingly is what https://gist.github.com/deepfire-pusher/fe13848dc810ada606e79964b3549418#file-exhibits-hs-L56-L61 should have provided.

However that exhibit (runnable by `runhaskell exhibit.hs 2`) ignores the `Tab`/`Shift+Tab` keypresses.

What works (in terms of focus changes), instead is https://gist.github.com/deepfire-pusher/fe13848dc810ada606e79964b3549418#file-exhibits-hs-L32-L42 (runnable by `runhaskell exhibit.hs 1`), which breaks the not-really-a-loop (?) in the definition, and simulates user input with externally supplied events.

So, I was wondering if I am misunderstanding things, or if this is really a bug.

**Comment by deepfire-pusher** [comment]
Ok, so in the seemingly-anomalous case, the index of the focused list element seems to vary normally in `adjustFocus` (https://github.com/reflex-frp/reflex-vty/blob/develop/src/Reflex/Vty/Widget/Layout.hs#L129) -- and it is found within the list.

Then it must be visualisation which is the problem.

**Comment by deepfire-pusher** [comment]
Ok, hmm, the `focussed` Dynamic (https://github.com/reflex-frp/reflex-vty/blob/develop/src/Reflex/Vty/Widget/Layout.hs#L141) seems to fire three times for a single `Shift+Tab` keypress, _and_ the redraw seems to be suppressed.

**Comment by deepfire-pusher** [comment]
Ok, a side-effect of adding plain `trace` expressions is that it exposes that indeed, in `exhibit2` we have the draws suppressed, for some reason (while the focus changes still work, as mentioned previously).

**Comment by deepfire-pusher** [comment]
So, in `exhibit2`, the redraws don't happen during focus shift events, but `updateVty` is called in `runVtyAppWithHandle`.

**Comment by deepfire-pusher** [comment]
Seeing that the vty's `Picture` has a list of layers -- `exhibit1` and `exhibit2` do not have different layer counts -- yet no redraws for the latter.

The plot gets thicker..

**Comment by deepfire-pusher** [comment]
Hmm, updating to current `reflex` seems to have fixed the problem.

Should have done this sooner!

**Comment by deepfire-pusher** [comment]
Ok, after more tracing of `runLayout` it became clear that the focus change event gets overridden by a default focus change on widget build, which is unclear if it's a bug.
