### ISSUE TITLE
How to use this package as a dependency?

### ISSUE THREAD

**Issue by Elvecent** [reflex-frp/reflex-vty#18]
I'm using Nix to manage dependencies and Cabal to build my packages inside a Nix shell. This package is marked as broken in nixpkgs (as reflex-related packages normally are) so I've tried to use a local copy cloned from this repository. However, I can't figure out which Nix expression exactly describes the package so I can put it in package overrides. I understand it is somehow generated with cabal2nix as described in `release.nix`? 

This is what I've tried:
```
config = {
    packageOverrides  = p: rec {
      haskellPackages = p.haskellPackages.override {
        overrides = self: super: rec {
          reflex-vty = import ../reflex-vty/release.nix {};
        };
      };
    };
  };
```

This normally works with other packages, but `reflex-vty` isn't found inside the shell.

**Comment by alexfmpe** [comment]
You could get it directly from hackage with `callHackage`, or use `callCabal2nix` on a local path / github repo (`fetchFromGitHub`).
Reflex-platform has some [examples](https://github.com/reflex-frp/reflex-platform/blob/85d986dba1992e20b7c5adfa8a3fec29098da7da/haskell-overlays/reflex-packages/default.nix#L100-L108)

**Comment by Elvecent** [comment]
@alexfmpe OK, I see that for this to work I'll need the reflex package proper which in turn does not build easily. I guess it's reasonable to rely on reflex-platform in its entirety. I will now try to set it up as described in [project-development.md](https://github.com/reflex-frp/reflex-platform/blob/develop/docs/project-development.md)
