### ISSUE TITLE
[request] upgrade to reflex 0.7.0.0

### ISSUE THREAD

**Issue by pdlla** [reflex-frp/reflex-vty#20]
Would love to use this for my project which is already half written in 0.7.0.0.

**Comment by pdlla** [comment]
I was able to get this to work in 0.7.0.0. The only change needed was adding `liftIO` on line 117 in Reflex/Vty/Host.hs

`displayRegion0 <- liftIO $ V.displayBounds $ V.outputIface vty`

I also upgraded several other of the dependencies with no issues. I could make PR for this but I'm very unfamiliar with cabal and feel like I set the upgraded versions incorrectly. I was able to verify this works by running the example in src-bin in a stack project that depends the fork I made with the changes.

**Comment by 3noch** [comment]
Thank you for testing! I would expect the 0.7 compatibility to be uneventful.

**Comment by pdlla** [comment]
looks like this was fixed in https://github.com/reflex-frp/reflex-vty/pull/22
