### ISSUE TITLE
Feature Request: Password Text Field

### ISSUE THREAD

**Issue by jfischoff** [reflex-frp/reflex-vty#3]
I'm coming from the `brick` world where one can modify an text input to display the entered text as all "****"s for entering passwords. 

I would like to do the same thing with `textInput` but I can't figure how. Hopefully there is a way and I just missed it, but I think I would need to be able to alter how the `displayLines` operates. 

`brick` implements it's text editor with a generic function that allows one to pass in a `[T.Text] -> Widget n` to control the rendering of the text. I suppose `reflex-vty` do something similar (although with different types)

I don't have a strong opinion on whether this is a good approach or not. I mostly want to be able to type passwords with '*' somehow. 

Thanks for making this by the way. I'm enjoying creating my simple form thus far.

**Comment by cgibbard** [comment]
We don't yet have a password entry widget, but it's a good idea. It'd probably be simplest just to provide a way to disable rendering of the text, and then if you want to render an appropriate number of stars on top, that'd be simple. Another very general option which would be easy to implement would be to have a `Behavior t (TextZipper -> TextZipper)` which is applied to the current state of the widget before rendering it.

**Comment by ali-abrar** [comment]
Should be addressed by #7

**Comment by ali-abrar** [comment]
Fixed in 0.1.2.0
