### ISSUE TITLE
V.defAttr Behavior in VtyWidgetCtx 

### ISSUE THREAD

**Issue by pdlla** [reflex-frp/reflex-vty#41]
# Problem
Currently, it's difficult to apply a styling to all widgets. Adhering to the widgets provided, it requires manually calling styled variants like `text'` (which don't exist for all widgets e.g. `boxTitle`) with a "default" `V.attr` Behavior that must be passed in throughout the program.

# Proposed Solution
Create a new parameter ` _vtyWidgetCtx_defaultAttr` in `VtyWidgetCtx`that's used instead of V.defAttr across all built-in widgets.

Sample implementation https://github.com/reflex-frp/reflex-vty/pull/42

# Issues
Notably, a little awkward if the user wants to specify a default "cursor" attribute or default "clicked" attribute (say). These could be hardwired into `VtyWidgetCtx` as with `_vtyWidgetCtx_defaultAttr`. Perhaps something like a `V.Attr` map would be appropriate? It kind of sucks to wrap VtyWidget in a Reader Monad for user defined attribute groups as well so it's nice to have some built-in.

**Comment by pdlla** [comment]
BTW, I'd love to implement this right away. This feature is blocking the work I'm doing and would be rather difficult to maintain on my own fork while updating the other PRs I'm trying to merge.

**Comment by ali-abrar** [comment]
Closed via #44
