### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by reubenharry** [reflex-frp/reflex-vty#51]
Following the readme instructions, I get (when running nix-shell):

```
error: attribute 'stdenv' missing

       at /nix/store/bblbjmnzbzfib5q0r7xbk1c920bsabbw-source/pkgs/build-support/cc-wrapper/default.nix:62:8:

           61|   expand-response-params =
           62|     if buildPackages.stdenv.hasCC && buildPackages.stdenv.cc != "/dev/null"
             |        ^
           63|     then import ../expand-response-params { inherit (buildPackages) stdenv; }
```

If I try to install with stack, I get other errors.

Are these installation methods working for other people (i.e. is it a problem on my end) or is the repo out of date?

Thanks so much!

**Comment by Ericson2314** [comment]
You are on a newer version of Nix than the one we have tested with. If you want to use Nix that's great, but otherwise I would just use cabal or stack.

Cross compiling (GHCJS, mobile apps) is currently highly complex and best done with Nix and something like reflex-platform or haskell.nix, but native compiling works well enough out of the box so there should be no pressure to use Nix.

**Comment by reubenharry** [comment]
Ah, thanks! I tried making a new stack project, with lts-16.27 (ghc 8.8.4) and adding reflex-vty to the package list. Stack then asked me to add the following extra-deps:

```
- reflex-vty-0.2.0.0@sha256:2a136962687d7066ba8b826147adb22eb4936c57c3bacec15cec0d93cf5265e2
- dependent-map-0.4.0.0@sha256:ca2b131046f4340a1c35d138c5a003fe4a5be96b14efc26291ed35fd08c62221,1657
- dependent-sum-0.7.1.0@sha256:0e419237f5b86da3659772afff9cab355c0f8d5b3fdb15a5b30e673d8dc83941,2147
- ref-tf-0.4.0.2@sha256:69de3550250e0cd69f45d080359cb314a9487c915024349c75b78732bbee9332,1134
- reflex-0.8.2.0@sha256:2ea3db2ed15b83eed6b15f7c1aaceeda9e783b611ac530032f6aeaf0d33b8ef0,11974
- constraints-extras-0.3.2.0@sha256:0897821d9d0428f41cf2179b2a8e99e0053e96a98dd39d91a31ab2851052338f,1777
- monoidal-containers-0.6.1.0@sha256:5a15cf46aaf4472ca6aa7f4e4fbab903a902e6f320a000a4a9e60a649e4381c8,2219
- patch-0.0.4.0@sha256:dc50de424d9ded983651f073b3862c190d927f8b155bececeb7b518cb5f99f5a,2486
- prim-uniq-0.2@sha256:7bfd8a729812bf212610b63459b76a086ecd5ce48f48d785c288e082d055d47b,1403
- witherable-0.3.5@sha256:9febcda439f514aec8f430bd3c75a7cda20b28978a8cbad1b2f8f097a3a16b42,1542
```
I then got the following error:

```
Error: While constructing the build plan, the following exceptions were encountered:

Dependency cycle detected in packages:
    [monoidal-containers,witherable,monoidal-containers,reflex,reflex-vty,refl]
...
```

**Comment by Ericson2314** [comment]
8.8 is old. Use 8.10. Or just use `cabal`. I did `cabal init` and added a `reflex-vty` app and it's building right now no issues.

**Comment by reubenharry** [comment]
Great, I'll try that. It build fine with cabal when I cloned the repo, so I think it should work from hackage. Very excited to play with it, and thanks again!

**Comment by Ericson2314** [comment]
No problem! Glad you are excited to try it out.
